### ISSUE TITLE
boa 0.3.2 fails to build and test noarch package

### ISSUE THREAD

**Issue by gabrielcnr** [mamba-org/boa#111]
`boa` version `0.3.2` is failing to build & test a conda package when it's `noarch: python`.

Consider the following recipe for a simple dummy package which is `noarch: python`

```yaml
package:
  name: foo
  version: "0.1.1"

build:
  noarch: python

requirements:
  build:
    - setuptools
  run:
    - python>=3.6,<3.7

test:     # we need whatever here just to force the creation of the test environment
  imports:
    - os
  requires:
    - pytest
```

Building the package above with:

```
mamba mambabuild .
```

gives the error message below (truncated):

```
...
INFO conda_build.utils:shutil_move_more_retrying(2091): shutil.move(work)=/Users/greis/conda/envs/boa032/conda-bld/foo_1610557324713/work, dest=/Users/greis/conda/envs/boa032/conda-bld/foo_1610557324713/work_moved_foo-0.1.1-py_0_noarch)
conda-forge/noarch       Using cache
Users/greis/conda/envs/b [====================] (00m:00s) Done
main/noarch              [====================] (00m:00s) No change
Users/greis/conda/envs/b [====================] (00m:00s) Done
Mamba failed to solve:
 - foo 0.1.1 py_0
 - python
 - pytest
 - python

with channels:
 - file:///Users/greis/conda/envs/boa032/conda-bld

The reported errors are:
⇟   Encountered problems while solving.
   Problem: nothing provides requested python
   Problem: nothing provides requested pytest
   Problem: nothing provides requested python
   Problem: nothing provides python >=3.6,<3.7 needed by foo-0.1.1-py_0
```

## Expected behaviour

When I use `boa=0.3.0` then it builds the `noarch` package without any problems. The `boa=0.3.2` also builds non-noarch packages fine. @wolfv So I think it's a problem related to `boa=0.3.2` and `noarch: python` packages.

## environment

The relevant packages on my environment are:

```
boa                       0.3.2            py38h50d1736_1    conda-forge
conda                     4.9.2            py38hecd8cb5_0    main
conda-build               3.20.5                   py38_1    main
mamba                     0.7.6            py38he6f4b85_0    conda-forge
python                    3.8.5                h26836e1_1    main
```
