### ISSUE TITLE
Packages are not moved to broken if the test stage fails to solve

### ISSUE THREAD

**Issue by chrisburr** [mamba-org/boa#137]
Packages which fail to solve for the test stage are left in `conda-bld/SUBDIR` when using `conda mambabuild`. This differs to the `conda build` behaviour which moves them to `conda-bld/broken/`.

This can be reproduced by creating `recipe/meta.yaml` and running `conda [mamba]build recipe`:

```yaml
package:
  name: example
  version: 0.0.1

build:
  number: 0
  script: "echo EXAMPLE >> $PREFIX/example.txt"

requirements:
  host:
    - python
  run:
    - python
  run_constrained:
    - python 9999

test:
  commands:
    - cat $CONDA_PREIFX/example.txt
```
