### ISSUE TITLE
mambabuild fails if the top level package depends on an output

### ISSUE THREAD

**Issue by chrisburr** [mamba-org/boa#201]
It seems recipes with multiple outputs fail to resolve the outputs if the top level recipe depends on them, `conda build` works for both cases.

There is a reproducer below that can be tested with:
```bash
# Need to clean the conda-bld directory first to prevent mamba from finding the build from a previous test
rm -rf ~/mambaforge/conda-bld/
conda mambabuild recipe --python=3.9
```

## Possible cause

I have a breakpoint on the `DependencyNeedsBuildingError` in my local install so I can poke around to debug conflicts.

Interestingly this excpetion only gets raised+queitly supressed when using conda-build with the failing recipe. This line is never executed for the example that works with `mambabuild`.

```
> /Users/cburr/mambaforge/lib/python3.9/site-packages/conda_build/environ.py(805)get_install_actions()
-> raise DependencyNeedsBuildingError(exc, subdir=subdir)
```

I suspect there is a missing bit of monkeypatching?

## Failing recipe

```yaml
package:
  name: uproot
  version: "4.1.6"

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python
    - {{ pin_subpackage('uproot-base', exact=True) }}

outputs:
  - name: uproot-base
    build:
      script:
        - touch $PREFIX/example-file
    requirements:
      host:
        - pip
        - python
      run:
        - python

  - name: uproot
```

## Passing recipe

```yaml
package:
  name: uproot-base
  version: "4.1.6"

build:
  number: 0
  script:
    - touch $PREFIX/example-file

requirements:
  host:
    - pip
    - python
  run:
    - python

outputs:
  - name: uproot-base

  - name: uproot
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('uproot-base', exact=True) }}
```
