### ISSUE TITLE
[mambabuild] fix multi-output once more

### ISSUE THREAD

**Issue by wolfv** [mamba-org/boa#210]
There is an issue where a MatchSpec shoudl be a string here:

ref https://github.com/conda-forge/staged-recipes/pull/16814

```
{% set name = "ocp" %}
{% set version = "7.5.2beta" %}
{% set occt_version = "=7.5.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # The release .tar.gz does not contain the requisite `pywrap` submodule, use 
  # the tagged git version for now

  # url: "https://github.com/CadQuery/OCP/archive/refs/tags/7.5.2-beta.tar.gz"
  # sha256: 616303149564dae4628b7f536ccfdd245cf397eaf8b3c1b2f724d517c99ac171

  git_url: https://github.com/CadQuery/OCP.git
  git_rev: 7.5.2-beta

build:
  number: 0

test:
  imports:
    - OCP

outputs:
  - name: ocp-devel
    script: generate-bindings.sh
    requirements:
      host:
        - python
        - clangdev
        - clang =10.0.1
        - pybind11
        - pybind11-abi
        - occt {{ occt_version }}
        # binder requirements
        - joblib
        - toml
        - click
        - cymbal
        - jinja2
        - logzero
        - pandas
        - path.py
        - pyparsing
        - schema
        - tqdm
        - toposort

  - name: {{ name }}
    script: compile-bindings.sh
    requirements:
      build:
        - python
        - cmake
        - ninja
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('libxi-devel') }}       # [linux]
        - {{ cdt('libxext-devel') }}     # [linux]
      host:
        - python
        - pybind11
        - "{{ pin_subpackage('ocp-devel', exact=True) }}"
        - occt {{ occt_version }}
      run:
        - python
        - occt {{ occt_version }}
        - "{{ pin_subpackage('ocp-devel', exact=True) }}"


about:
  home: https://github.com/CadQuery/OCP/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python wrapper for OCCT using auto-generated pybind11 bindings.'
  doc_url: https://github.com/CadQuery/OCP/blob/master/README.md
  dev_url: https://github.com/CadQuery/OCP/

extra:
  recipe-maintainers:
    - whophil
    - adam-urbanczyk
```
