### ISSUE TITLE
Recipe which fails to build with `conda mambabuild` but succeeds with `conda build`

### ISSUE THREAD

**Issue by whophil** [mamba-org/boa#226]
I have a recipe which fails to build with `conda mambabuild` but suceeds with plain old `conda build`.

`mambabuild` fails when trying to resolve the environment in which to build `mypackage-docs`.
```
- Encountered problems while solving:
-   - package mypackage-0.0.1-py38_0 requires hdf5 1.10.6 *1114, but none of the providers can be installed
```

A minimal version of the recipe is listed below, and is also in the attached .zip

I suspect this may be related to the `hdf5` dependency, as there seem to be some conda/mamba differences relating to how environments with this package are resolved.
- https://github.com/h5py/h5py/issues/1880
- https://github.com/conda-forge/h5py-feedstock/issues/92

```yaml
package:
  name: mypackage-suite
  version: 0.0.1

source:
  path: .

outputs:
  - name: mypackage
    script: build_mypackage.sh
    requirements:
      build:
        - cmake =3.18
        - gxx_linux-64 9.*        # [linux]
        - python {{ python }}
      host:
        - python {{ python }}
      run:
        - python {{ python }}
        - vtk

        # https://github.com/conda-forge/vtk-feedstock/issues/207
        - hdf5 1.10.6 *1114  

  - name: mypackage-docs
    requirements:
      build:
        - python {{ python }}
        - sphinx
        - {{ pin_subpackage("mypackage", exact=True) }}
```

[mypackage.recipe.zip](https://github.com/mamba-org/boa/files/7789751/mypackage.recipe.zip)
