### ISSUE TITLE
Matrix expansion with pinned subpackages

### ISSUE THREAD

**Issue by wolfv** [mamba-org/boa#232]
We sometimes have a situation where a package is exactly pinning a subpackage and the pinned subpackage has multiple variants. If the matrix is not the same for the pacakge & subpackage, only one package might be created. 

E.g. 

conda_build_config.yaml

```
A:
- 1.0
- 2.0
```

```
outputs:
   package:
      name: x1
   dependencies:
      run:
         - A
    package:
       name: x2
     dependencies:
        run:
            - {{ pin_subpackage('x1', exact=True) }}
```

We should either warn or automatically expand the matrix for x2 with all variants of x1.
