### ISSUE TITLE
[recipe-spec] Allow for arbitrary optional dependencies

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/boa#245]
### Proposal:
Have a single top-level `requirements` section as there is currently with required keys `host` and `run` and then optionally allow ***any other keys*** to specify named dependencies.

A `requirements.build` key would then be handled the same as currently but test dependencies would now be included as an optional `requirements.test` key. The specification of test dependencies under `requirements.test` would then be consistent with the specification of other dependencies under `requirements` (e.g. `requirements.build` rather than `build.requirements`)

In this way `mamba/boa` could provide support for the [`extras_require`](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html?highlight=extra#optional-dependencies) capability in `setuptools`/`pip` which is very widely used, and very useful.

Similar to `setuptools`, having a special-cased test requirements section could be removed in favour of treating them like any other optional dependency:
![image](https://user-images.githubusercontent.com/881019/154468909-ed6dc5a1-5c69-4aa6-b4b7-0a20416da381.png)

To get the benefit of this new capability would require all the requirements to be saved in the package metadata and for `mamba` to allow users to install *any* named dependencies in the package metadata.

Currently, it's very awkward for users to create either a build or test environment as there's no way to tell `mamba` to create an environment with those specific deps.

The current recommendation to instead create separate *outputs* for any optional dependencies is awkward to specify and clutters up package repositories with multiple metadata-only packages for every single build.

**Comment by dhirschfeld** [comment]
This is mostly a re-hashing of my arguments in the original [hackmd document](https://hackmd.io/axI1tQdwQB2pTJKt5XdY5w#Dave-Hirschfeld-Optional-Dependencies) as a GitHub issue may provide a better forum for feedback and discussion.

**Comment by dhirschfeld** [comment]
...and having just written this I now see https://github.com/conda/ceps/pull/9

**Comment by dhirschfeld** [comment]
Example from [`dask`](https://github.com/dask/dask/blob/bd8e8dc3f1329e7f9ef24072479729d9effeb6ad/setup.py#L14-L41):
```python
extras_require: dict[str, list[str]] = {
    "array": ["numpy >= 1.18"],
    "bag": [],  # keeping for backwards compatibility
    "dataframe": ["numpy >= 1.18", "pandas >= 1.0"],
    "distributed": ["distributed == 2022.02.0"],
    "diagnostics": [
        "bokeh >= 2.1.1",
        "jinja2",
    ],
    "delayed": [],  # keeping for backwards compatibility
}
extras_require["complete"] = sorted({v for req in extras_require.values() for v in req})
# after complete is set, add in test
extras_require["test"] = [
    "pytest",
    "pytest-rerunfailures",
    "pytest-xdist",
    "pre-commit",
]

install_requires = [
    "cloudpickle >= 1.1.1",
    "fsspec >= 0.6.0",
    "packaging >= 20.0",
    "partd >= 0.3.10",
    "pyyaml >= 5.3.1",
    "toolz >= 0.8.2",
]
```

```yaml
requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7
    - cloudpickle >=1.1.1
    - fsspec >=0.6.0
    - packaging >=20.0
    - partd >=0.3.10
    - pyyaml >=5.3.1
    - toolz >=0.8.2
  run_constrained:
    - openssl !=1.1.1e
  array:
    - numpy >=1.18
  complete:
    - dask[array]
    - dask[dataframe]
    - dask[diagnostics]
    - dask[distributed]
  dataframe:
    - dask[array]
    - pandas >=1.0
  diagnostics:
    - bokeh >=2.1.1
    - jinja2
  distributed:
    - distributed ==2022.02.0
  test:
    - pytest
    - pytest-rerunfailures
    - pytest-xdist
    - pre-commit
 ```

**Comment by wolfv** [comment]
Hey, I think we could quite easily create additional outputs for a given recipe inside of boa that reference the top-level recipe using `pin_subpackage(exact=true)` automatically. It would be a cool exercise!
For the final package name we could either use a valid syntax for the package name like `dask[array]` maps to `dask-array`, or if we want to make sure to not duplicate names we could go for `dask__array__` or something crazy like that. Or we could allow `[` in the package name (although I don't know if that maps well on all operating systems to file & folder names).

I am not sure if I would want to have this as additional top-level requirements keys or if we should put it as a next level under the `run` key.

**Comment by wolfv** [comment]
Regarding moving the `test` requirements under the `requirements.test` (instead of `test.requires`) is something I thought about today and maybe that's the first step into this direction, actually.

**Comment by h-vetinari** [comment]
> Example from [`dask`](https://github.com/dask/dask/blob/bd8e8dc3f1329e7f9ef24072479729d9effeb6ad/setup.py#L14-L41):

I find the proposed recipe-syntax (same level as build/host/run) confusing and otherwise less-than-ideal. Could this not be in a dedicated requirements-section like `extensions:`?

**Comment by wolfv** [comment]
So, I've been thinking about this a little bit more and even today it's already possible to quite easily create a couple of subpackages using explicit outputs and run requirements:

```yaml
context:
  name: dask
  version: 0.1.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

build:
  number: 0

outputs:
  - package:
      name: dask
    requirements:
      host:
        - python
      run:
        - python
  - package:
      name: dask-array
    requirements:
      run:
        - "{{ pin_subpackage('dask', exact=True) }}"
        - numpy >=1.14
  - package:
      name: dask-dataframe
    requirements:
      run:
        - "{{ pin_subpackage('dask-array', exact=True) }}"
        - pandas
```

The way boa works it's _extremely_ fast to produce the additional two outputs (basically takes no time) because of some architectural changes in boa vs. conda-build.

If we'd come up with a more concise syntax it would anyways be pre-processed into the above syntax, essentially. The magic pieces would be to automatically add the `pin_subpackage exact` and expand the names from a shorter form.

I think right now the bracket syntax won't work in conda/mamba/boa.
If we specify that we allow the bracket syntax in repodata.json / packages etc. that would probably the only thing that we really need as a CEP.

Mamba should have additional logic to translate `dask[array, dataframe]` to `dask[array] dask[dataframe]`.
