### ISSUE TITLE
Spec discussion

### ISSUE THREAD

**Issue by wolfv** [mamba-org/boa#248]
Notes from an virtual spec discussion we just had over Zoom:

### Other syntax for `sel(...)`

Replace 

```yaml
- sel(linux): xtensor
```

with 

```yaml
- if: linux
   put: xtensor
```

(this should also work for list, e.g. 

```yaml
- if: linux
  put:
  	- xtensor
  	- xsimd
  	- ...
```

To skip certain steps, we will use

```yaml
    if:
      - unix and py > "3.6"
      - unix and py > ver("3.6")
      - unix and vercmp(py, "3.6")
    # implies `put: {skip: true}` when used at a top-level step key
```

The recursive parsing logic for this will stay exactly the same. 

We can extend that eventually to for loops:

```yaml
- for: element in mylist
   put: {{ element[0:10] }}
```

### Rename outputs to `tasks` or `steps`

And furthermore, make sure that _not each step has to produce a package!

A package is only produced if the step has a `package` key.
Otherwise, there can be build output produced (for later splitting) or it can be used to run non-output specific tests (the tests can require other outputs from the recipe).

```yaml
steps:
- step:
    name: buildstep
  requirements:
    build:
      - "{{ compilers('cxx') }}"
    host:
      - libcpp
      - libxnd
- package:
    name: libx
    version: "1.2.3"
  requirements:
    stepresult:
      # note: this needs to make sure that the 
      #.      proper variant is selected!
      - buildstep
    run:
      - something
    test:
      - otherpkg
  test:
    commands:
      - checklibx
- test:
    name: supertest
    commands:
      - pip check
  requirements:
    test:
      - libx
```

### Replace Jinja functions with YAML dictionary

Instead of writing `{{ compiler('cxx') }}` it was suggested to write `compiler: cxx`.

Other currently used functions:

```
# All currently availble jinja functions in boa:

- compiler: cxx
- compiler: fortran
- cdt: xorg-libx11
- run_exports:
    - pin_subpackage:
        name: "{{ name }}"
        # default optional values below
        max_pin: "x.x.x.x.x"
        exact: false
requirements:
  run:
    - pin_compatible:
        name: xtensor
        # default values below
        lower_bound: null
        upper_bound: null
        min_pin: "x.x.x.x.x.x"
        max_pin: "x"
        exact: false

# this is pretty actually useless, we should probably keep it a jinja function or put all env vars into the context to make them usable from jinja anyways
# although we could have a special section in `context` where you can add env vars (similar to github actions)
- environ: MYXPKG_VERSION
```

**Comment by wolfv** [comment]
I went ahead and test-implemented the `steps` syntax to something like this:

<detail><summary>Recipe with multiple steps + splitting</summary>

```yaml
context:
  name: multistep
  version: 0.7.3

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

build:
  number: 0

steps:
  - step:
      name: buildstep
    build:
      script:
        - echo "File 1" > file_1.txt
        - echo "File 2" > file_2.txt
        - echo "File 3" > file_3.txt

  - package:
      name: multistep-a
      version: 1.2.3
    source:
      - step: buildstep
    build:
      script:
        - cp file_1.txt $PREFIX/file_1.txt

  - package:
      name: multistep-b
      version: 1.2.3
    source:
      - step: buildstep
    build:
      script:
        - cp file_2.txt $PREFIX/file_2.txt
        - cp file_3.txt $PREFIX/file_3.txt
```
</detail>

However, I also noticed some issues, especially around variants, requirements & run_exports.
I am working on additional visualizations right now so we can make sure that we get it right. Basically, the dependee needs to inherit variants & run exports and stuff like this.
