### ISSUE TITLE
cdt function does not respect variant cdt_name

### ISSUE THREAD

**Issue by mariusvniekerk** [mamba-org/boa#284]
When you have a build using a conda_build_config that is say something like

```yaml
# conda-build-config.yaml
cdt_name:
  - cos7
```

```yaml
# recipe.yaml
requirements:
  host:
     - "{{ cdt('numactl-devel') }}"
```

then boa will false try to use the `cos6` version of the cdt and fail in this case since it does not exist.
