### ISSUE TITLE
Incorrect type for `script_env`?

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/boa#298]
I want to pass through the `SETUPTOOLS_SCM_PRETEND_VERSION` env var to the build so tried specifying it in the `build.script_env` section:
```yaml
build:
  number: 0
  script: $PYTHON -m pip install . -vv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION
```

However, it seems that `boa` doesn't allow this:
```
Recipe validation error

['SETUPTOOLS_SCM_PRETEND_VERSION'] is not of type 'object'

Failed validating 'type' in 
schema['properties']['build']['properties']['script_env']:
    {'additionalProperties': {'type': 'string'},
     'title': 'Script Env',
     'type': 'object'}

On instance['build']['script_env']:
    ['SETUPTOOLS_SCM_PRETEND_VERSION']

Recipe validation not OK. This is currently ignored.
```

IIUC this should be allowed?
https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#inherited-environment-variables

It appears that `boa` expects this to be a key/value mapping instead of an array of names whose values will be set from the calling environment.
