### ISSUE TITLE
Multiple build with boa

### ISSUE THREAD

**Issue by ffirmanff** [mamba-org/boa#308]
First off, hats off to @wolfv and other mamba/boa project members.  This is a huge improvements in developer quality of life vs conda build.

I have a requirement to create multiple C++ builds in our pipeline using boa (e.g. build vs debug, static vs dynamic).
With `conda build`, I can specify the variants in the `conda_build_config.yaml` file like such:
```
buildtype:
  - debug
  - release
```
I can reference the buildtype as a variable in `meta.yaml` file directly like so:
``
build:
  string: 'build{{ buildtype }}'
  number: 0
  script_env:
    - CMAKE_BUILD_TYPE={{ buildtype }}
```
Conda build will take the vars and update the recipe accordingly.

However, if I were to do the same in boa's `recipe.yaml`, I find that the variables from the `conda_build_config.yaml` are not accessible, and really only useable as version references for packages that matched the variable name. 

Peeking through the codes, seems boa parses out the `recipe.yaml` alone (without using any values from the variants), and replaces non-matching jinja2 variables with blank.  Only later is the variants from `conda_build_config.yaml` used to apply the versions against matching packages.

1. Can someone please help explain the reasoning for changing the logic this extensively?  I had read the reasoning for simplifying the recipe format, but this seems a bit drastic.
2. What is the recommendation for how I can create separate debug and release build of my packages?

**Comment by wolfv** [comment]
Hi @ffirmanff thanks for the kind words!

Indeed, I have an open PR to tackle this here: #261 

I haven't yet gotten around to finish it -- if you have cycles to put into this that would be awesome.

You can do it today with a simple script that would change the YAML file (it's very easy to manipulate because it's proper YAML :)

One reason for changing some of the logic is that conda-build is evaluating the recipes recursively which makes it really slow. However, I think we could make this jinja-variant logic work without having to go down real recursions.

**Comment by ffirmanff** [comment]
Happy to contribute @wolfv !
I was trying to figure out where to make the changes, but got lost, so perhaps you can help clarify things a bit.
From what I understand:
1. The `recipe.yaml` is parsed and flattened here: https://github.com/mamba-org/boa/blob/main/boa/core/run_build.py#L492
2. But the variants from `conda_build_config.yaml` only gets applied here: https://github.com/mamba-org/boa/blob/main/boa/core/run_build.py#L500

What is the best way to do this?  (apology if I have the terms wrong)
* I can't apply the build variants in step 1, because if there are multiple variants then I will need to keep multiple recipe variants, and carry them into step 2.
* Alternatively, do not (jinja) parse the `recipe.yaml` in step 1, so that we keep all the jinja2 references.  But in step 2 when the build variant permutations are being generated, a copy of the 'recipe.yaml' is parsed using the variant permutation variables first, before applying the variant permutation.

**Comment by wolfv** [comment]
Awesome, yes, I think those were exactly the problems that I was hitting. 

I think I was attempting to keep the un-evaluated jinja in a adapted string, and then apply it with the variant evaluation. 

But it feels like we need another "loop" where we first check the recipe for all used jinja variables. The easiest would be to use "regular" jinja to insert those in the "text" form of the recipe (instead of carrying them with us in that modified string.

I think we can add a step where we try to find the jinja variables, then add them to the context and render the recipe as normal, execute the build, and repeat for other jinja options.

**Comment by wolfv** [comment]
^ That would be different from what I've attempted in #261 but maybe more straightforward to implement.

**Comment by ffirmanff** [comment]
Sorry haven't had a chance to look into this, been a bit tied up at work, but will hopefully come back next week.

**Comment by harelwa** [comment]
Hi,

I'm encountering ( perhaps ) a similar issue, which might also be related to https://github.com/mamba-org/boa/issues/318

When `boa` building for multiple `py` versions, the variants versions are not "inserted" to the built packages requirements.

env info - 

```bash
(base) > $ mamba list "(boa|mamba|conda)"
# packages in environment at /Users/harelos/mambaforge:
#
# Name                    Version                   Build  Channel
boa                       0.14.0             pyhd8ed1ab_0    conda-forge
conda                     22.11.1         py310h2ec42d9_1    conda-forge
conda-build               3.23.3          py310h2ec42d9_0    conda-forge
conda-package-handling    1.8.1           py310h1961e1f_1    conda-forge
conda-souschef            2.2.3              pyhd8ed1ab_0    conda-forge
libmamba                  1.1.0                h8b63968_2    conda-forge
libmambapy                1.1.0           py310hb15139c_2    conda-forge
mamba                     1.1.0           py310h6bde348_2    conda-forge
```

`recipe.yaml` - 

```yaml
context:
  name: hera-workflows
  version: 4.3.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hera_workflows-{{ version }}.tar.gz
  sha256: 30976fe13de04d803d430825721532921f5b18edbd90b861e5d69b0ba8123859

build:
  script: '{{ PYTHON }} -m pip install . -vv'
  number: 0

requirements:
  build:
    - python {{ python }}
  host:
    - python
    - pip
    - poetry
  run:
    - python
    - argo-workflows ==6.3.5
    - certifi >=2021.10.8
    - python-dateutil >=2.8.2
    - pytz >=2021.3
    - urllib3 >=1.26.8
    - typing-extensions >=3.10.0

test:
  imports:
    - hera
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/argoproj-labs/hera-workflows
  summary: Hera is a Python framework for constructing and submitting Argo Workflows. The main goal of Hera is to make Argo Workflows more accessible by abstracting away some setup that is typically necessary for constructing Argo workflows.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - harelos
```

`conda_build_config.yaml` - 

```yaml
python:
  - 3.9
  - 3.10
```

Build + Build results - 

```bash
(base) > $ boa build ./ --output-folder /tmp/boa-build --no-test 
[...]

(base) > $ mamba search "hera-workflows" -c /tmp/boa-build --override-channels --info

Loading channels: done
hera-workflows 4.3.0 py310h8ff6bd7_0
------------------------------------
file name   : hera-workflows-4.3.0-py310h8ff6bd7_0.tar.bz2
name        : hera-workflows
version     : 4.3.0
build       : py310h8ff6bd7_0
build number: 0
size        : 104 KB
subdir      : osx-64
url         : file:///tmp/boa-build/osx-64/hera-workflows-4.3.0-py310h8ff6bd7_0.tar.bz2
md5         : 5ce2329a058821da13de8e60521b897b
timestamp   : 2022-12-27 08:07:42 UTC
dependencies: 
  - argo-workflows ==6.3.5
  - certifi >=2021.10.8
  - python
  - python-dateutil >=2.8.2
  - python_abi 3.10.* *_cp310
  - pytz >=2021.3
  - typing-extensions >=3.10.0
  - urllib3 >=1.26.8


hera-workflows 4.3.0 py39h59b1b0c_0
-----------------------------------
file name   : hera-workflows-4.3.0-py39h59b1b0c_0.tar.bz2
name        : hera-workflows
version     : 4.3.0
build       : py39h59b1b0c_0
build number: 0
size        : 102 KB
subdir      : osx-64
url         : file:///tmp/boa-build/osx-64/hera-workflows-4.3.0-py39h59b1b0c_0.tar.bz2
md5         : 1988dc937d2913412e8e9dbd2f05fc2b
timestamp   : 2022-12-27 08:07:16 UTC
dependencies: 
  - argo-workflows ==6.3.5
  - certifi >=2021.10.8
  - python
  - python-dateutil >=2.8.2
  - python_abi 3.9.* *_cp39
  - pytz >=2021.3
  - typing-extensions >=3.10.0
  - urllib3 >=1.26.8
```

Whereas, when running `conda-build` for the following `meta.yaml` - 

```yaml
{% set name = "hera-workflows" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hera_workflows-{{ version }}.tar.gz
  sha256: 30976fe13de04d803d430825721532921f5b18edbd90b861e5d69b0ba8123859

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python {{ python }}
  host:
    - python
    - pip
    - poetry
  run:
    - python
    - argo-workflows ==6.3.5
    - certifi >=2021.10.8
    - python-dateutil >=2.8.2
    - pytz >=2021.3
    - urllib3 >=1.26.8
    - typing-extensions >=3.10.0

test:
  imports:
    - hera
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/argoproj-labs/hera-workflows
  summary: Hera is a Python framework for constructing and submitting Argo Workflows. The main goal of Hera is to make Argo Workflows more accessible by abstracting away some setup that is typically necessary for constructing Argo workflows.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - harelos
```

Build + Build results -

```bash
(base) > $ conda-mambabuild ./meta.yaml --output-folder /tmp/conda-build-out/ 

[...]

(base) > $ mamba search -c /tmp/conda-build-out --override-channels --info

Loading channels: done
hera-workflows 4.3.0 py310_0
----------------------------
file name   : hera-workflows-4.3.0-py310_0.tar.bz2
name        : hera-workflows
version     : 4.3.0
build       : py310_0
build number: 0
size        : 104 KB
license     : MIT
subdir      : osx-64
url         : file:///tmp/conda-build-out/osx-64/hera-workflows-4.3.0-py310_0.tar.bz2
md5         : 4690f05089a053ce892448ee27113e06
timestamp   : 2022-12-27 08:03:39 UTC
dependencies: 
  - argo-workflows 6.3.5
  - certifi >=2021.10.8
  - python >=3.10,<3.11.0a0
  - python-dateutil >=2.8.2
  - python_abi 3.10.* *_cp310
  - pytz >=2021.3
  - typing-extensions >=3.10.0
  - urllib3 >=1.26.8


hera-workflows 4.3.0 py39_0
---------------------------
file name   : hera-workflows-4.3.0-py39_0.tar.bz2
name        : hera-workflows
version     : 4.3.0
build       : py39_0
build number: 0
size        : 103 KB
license     : MIT
subdir      : osx-64
url         : file:///tmp/conda-build-out/osx-64/hera-workflows-4.3.0-py39_0.tar.bz2
md5         : 53346e80d80b6d7d2ecb679d5fb6ef22
timestamp   : 2022-12-27 08:04:28 UTC
dependencies: 
  - argo-workflows 6.3.5
  - certifi >=2021.10.8
  - python >=3.9,<3.10.0a0
  - python-dateutil >=2.8.2
  - python_abi 3.9.* *_cp39
  - pytz >=2021.3
  - typing-extensions >=3.10.0
  - urllib3 >=1.26.8
```
