### ISSUE TITLE
Building a conda recipe with tests that send SIGINT to children fails with `mambabuild` but succeeds with `conda build`

### ISSUE THREAD

**Issue by woutdenolf** [mamba-org/boa#320]
Recently a conda-forge build of a python library [failed](https://github.com/conda-forge/pypushflow-feedstock/pull/10) and I traced it down to an issue with `mambabuild`.

The conda recipe contains tests and some tests fail with `conda mambabuild` but succeed with `conda build`. I stripped down to failing test to this (it sends SIGINT to a child process):

```
import os
import time
import signal
from multiprocessing import Queue
from multiprocessing import Process


def task(queue):
    try:
        time.sleep(10)
    except KeyboardInterrupt:
        queue.put(True)
        return
    queue.put(False)


def test_mambabuild():
    queue = Queue()
    proc = Process(target=task, args=(queue,))
    proc.start()
    time.sleep(1)
    os.kill(proc.pid, signal.SIGINT)
    proc.join()
    assert queue.get_nowait()
```

The recipe that fails (branch includes the stripped down test above)

```yaml
{% set name = "pypushflow" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://gitlab.esrf.fr/workflow/pypushflow.git
  git_rev: fix_tests_on_conda_forge

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9

test:
  imports:
    - pypushflow
  commands:
    - pip check
    - pytest --pyargs pypushflow.tests.test_mambabuild
  requires:
    - pip
    - pytest >=7
    - pytest-subtests >=0.4
    - psutil >=5.8
    - mongita >=1

outputs:
  - name: pypushflow

about:
  home: https://gitlab.esrf.fr/workflow/pypushflow
  summary: A task scheduler for cyclic and acyclic graphs
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - woutdenolf
    - olofsvensson
    - payno
```
