### ISSUE TITLE
"about" section gets dropped during build

### ISSUE THREAD

**Issue by moqmar** [mamba-org/boa#322]
Hi there, I noticed that the packages built with boa (0.14.0) are missing the "about" section from the recipe.yaml. I'd expect the built package to contain e.g. "summary" (but also documentation URLs etc.) in `info/about.json`, but this is not the case.

A simple recipe.yaml for reproduction:
```yaml
package:
  name: "example"
  version: "0.0.0"

about:
  summary: "Hello World"

build:
  script: ["echo Hello World"]

requirements:
  build: []
  run: []
```
