### ISSUE TITLE
Test dependencies ignored when include_recipe is false

### ISSUE THREAD

**Issue by moqmar** [mamba-org/boa#328]
When setting `include_recipe: false`, boa won't install the test dependencies before running the test scripts.

I have crafted the following minimal recipe to reproduce the bug:

```yaml
package:
  name: test
  version: 1.0.0

build:
  include_recipe: false
  script: []

test:
  requires:
    - pyserial
  commands:
    - python -c "import pyserial"
```

As a workaround, I modified [`run_build.py` from line 395](https://github.com/mamba-org/boa/blob/main/boa/core/run_build.py#L395) like this, but I am not sure if that has other implications e.g. with multi-output packages:

```python
                    if not notest:
                        o.config.need_cleanup = False
                        run_test(
                            MetaData(final_out, o),
                            o.config,
```
