### ISSUE TITLE
Allow for more than one license, including directories

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/boa#341]
When specifying multiple license files like below:
```yaml
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - NOTICE.md
```
`boa` throws the below error:
```
Recipe validation error

['LICENSE', 'NOTICE.md'] is not of type 'string'

Failed validating 'type' in schema['properties']['about']['properties']['license_file']:
    {'title': 'License File', 'type': 'string'}

On instance['about']['license_file']:
    ['LICENSE', 'NOTICE.md']
```

With `conda-build` multiple license files and also directories are allowed. This is important to be able to specify 3rd party licenses which should be included.
