### ISSUE TITLE
mambabuild: requirement on python>=3.10.6 only built for python 3.11

### ISSUE THREAD

**Issue by dylon** [mamba-org/boa#363]
Hi, I have a `meta.yaml` script for `mambabuild` with the following `requirements` section:

```yaml
requirements:
  host:
    - pip
    - python>=3.10.6
    - setuptools=65.5.0
  run:
    - Cerberus=1.3.4
    - Jinja2=3.1.2
    - PyYAML=6.0
    - click=8.1.6
    - numpy=1.25.1
    - python>=3.10.6
    - reactivex=4.0.4
```

When I build it with `mambabuild`, I expect a package or multiple packages that may be used for python 3.10 or python 3.11, however only a package for python 3.11 is created. How may I target multiple python versions?
