### ISSUE TITLE
additional test macro: check file, check directory

### ISSUE THREAD

**Issue by wolfv** [mamba-org/boa#71]
It would be good to have additional functionality in boa / conda-build to easily check for the existence of a file / directory in the output. 

Currently this is pretty cumbersome with `test -f ...` etc.

**Comment by wolfv** [comment]
cc @martinRenou you might have ideas for this ...

**Comment by martinRenou** [comment]
You mean replacing `test/command: "test -f filename"` with something like `test/file: "filename"` in the recipe format?

**Comment by wolfv** [comment]
yeah maybe?

```
test:
    files_exist:
        - test.py
    directories_exist:
        - dirname/abc
```

IDK to be discussed.
