### ISSUE TITLE
Easy file-tests macros

### ISSUE THREAD

**Issue by wolfv** [mamba-org/boa#93]
Some ideas for easier writing tests. Currently people do stuff like 

- test -f $PREFIX/include/mamba/test.hpp  # [unix]
- if not %LIBRARY_PREFIX%\include\mamba\test.hpp exit 1 # [win]

which is super error prone and hard to get right.

### Ideas for "files" macros:

- `site-packages("mamba")` -> checks that pythonX.X/site-packages/<mamba> exists and has contents (at least one __init__.py)
- `pymodule("mamba")` -> checks that pythonX.X/site-packages/<mamba> exists and has contents (at least one __init__.py)
- `lib("libmamba", soversion="...")` -> check that at least `libmamba.so` / `libamamba.dylib` is found in `lib/`, additionally check for so-versions that link to that, or for windows, check that `bin/libmamba.dll` and `lib/libmamba.lib` are there
- `include("mamba")` -> check that include folder `include/mamba/` exists
- `include("mamba/test.hpp") -> check that file `include/mamba/test.hpp` exists in package
- `bin("mamba")

### I am unsure about the following ones:

- `cmake_find("mamba")` -> make sure that find_package("mamba") would work
- `pkgconfig("mamba")` -> make sure that pkgconfig mamba works

There are probably some good ideas to support other languages and their install prefixes. I don't know where R installs to?!

We can also use qualifiers to disallow any files outside those matched by the macros, except maybe files in `/share` or some other data-centric directory. That would give pretty strict control over the package content.

**Comment by mariusvniekerk** [comment]
We probably want to express this as something like

```yaml
- exists:
    site-packages: 
      - mamba
    pymodule:
      - mamba
    file:
       - $LIBRARY_PREFIX/some/file
    glob:
      - "**/another/file"
```

**Comment by marcelotrevisani** [comment]
I agree that @mariusvniekerk suggestion seems to be more straightforward

**Comment by marcelotrevisani** [comment]
I believe would be better to rename ``site-packages`` to ``python_modules``, maybe?

**Comment by chrisburr** [comment]
* I like the idea of the `cmake_find` and `pkgconfig`
* I'm not sure an existence macro for `site-packages`/`pymodule` is a common enough use case. Most packages should have `imports` specified already from which you can guess which files should exist.

**Comment by CJ-Wright** [comment]
@chrisburr how do they specify the `imports`?

**Comment by wolfv** [comment]
@chrisburr the idea would be to also check for files that should not be in the package (basically the inverse) and either strongly warn or error out if something is in there that shouldn't be. But we could totally implicitly use the imports tests to check that.

@CJ-Wright thats another test field where one can check that a python lib gets imported fine.

**Comment by chrisburr** [comment]
@wolfv There is always the option of using:

```yaml
- exists:
    file:
       - $SP_DIR/mamba/__init__.py
```

for the one or two exceptions where importing isn't possible because it needs to have a propitiatory shared library available or something.

**Comment by CJ-Wright** [comment]
I think we'd need more than just checking that a single file is imported, we'd need to check that all expected files are imported properly. In the past conda-forge's recipes haven't handled this well, leading to a bunch of issues on that front (and why I went and used the files themselves rather than the import tests to determine what modules are available)

**Comment by chrisburr** [comment]
@CJ-Wright I'm not sure quite what you're referencing? In the example:

```yaml
test:
  imports:
    - mamba
```

then roughly maps to the command `python -c 'import mamba'`. Is it that you want to explicitly check all submodules as well? i.e.

```yaml
test:
  imports:
    - mamba
    - mamba._version
    - mamba.mamba
    - mamba.mamba_env
    - mamba.repoquery
    - mamba.utils 
```
