### ISSUE TITLE
Multiple test sections in a single output?

### ISSUE THREAD

**Issue by chrisburr** [mamba-org/boa#94]
One of the issues with having a single `tests` sections in a single output is that adding test-only dependencies can result in broken packages sneaking out. For example:

```yaml
test:
    - requires:
        - pip
        - pytest
    - imports:
        - example
    - commands:
        - pip check
        - pytest -vvv
```

Possible failures are:
* If `example` depends on `pkg_resources` the `pip` requirement will provide `setuptools` at test time but not runtime.
* If `example` depends on `pluggy` the `pytest` requirement will satisfy the requirement at test time but not runtime.

I've seen this quite a few times both in Python packages and more complicated things. A possible solution would be to have three separate test sections and environments like:

```yaml
tests:
    # Basic import tests
    - imports:
        - example
    # Check dependencies
    - requires:
        - pip
      commands:
        - pip check
    # Unit tests
    - requires:
        - pytest
      commands:
        - pytest -vvv
```

Better yet, some of them could be marked as `optional`/`slow` to allow them to be skipped unless `--with-optional-tests` is passed to `conda build`/`boa`.

**Comment by wolfv** [comment]
Yeah, this makes sense. Another way to do this would also to perform import test without the test env specs... as a two step process, and add the additional specs later

**Comment by chrisburr** [comment]
> Another way to do this would also to perform import test without the test env specs... as a two step process, and add the additional specs later

I think it would be better to expose the stages explicitly because a implicit two-step process would still cause the `pip check` test command to incorrectly pass due to the presence of `pluggy`. Another possibly useful case might be:

```yaml
tests:
    # Basic import test with the latest Python
    - requires:
        - python >=3.9
      imports:
        - example
    # Basic import test for legacy Python
    - requires:
        - python =2.7
      imports:
        - example
```

I've also seen this happen for other languages (such as `compiler("cxx")` being added as a test requirement for building an example project). Imposing good style like "`test: imports` should in it's own test stage" is better left to a linter IMHO rather the complicating the build machinery with language specific special cases.
